### PR TITLE
fix random number generation

### PR DESCRIPTION
**Pull request by MuratovAS**
closes the problem with the random number generator #4

### CODE REVIEW

**Comment by zero88** [comment]
nice solution!!!

I think we can add `$RANDOM$RANDOM` to more challenges on random

**Comment by MuratovAS** [comment]
I checked the result of `$RANDOM` in different shells and distributions.
I noticed that `sh` `ubuntu` returns an empty string :(
I think that you should still check the presence of the result from `$RANDOM`.

image

**Comment by zero88** [comment]
Hi @MuratovAS , thank you for your suggestion.

I end up with this solution https://github.com/zero88/gh-release-downloader/pull/6/files#diff-e5063d34e04c6426439066619f412dad16db0301481fc3ba5c743af817a4946bR93-R94

Could you please verify [ghrd1.txt](https://github.com/zero88/gh-release-downloader/files/10712564/ghrd1.txt) to see if it works for you? (remove suffix `.txt`)

**Comment by MuratovAS** [comment]
yes it works for me.

> Hi @MuratovAS , thank you for your suggestion.
> 
> I end up with this solution https://github.com/zero88/gh-release-downloader/pull/6/files#diff-e5063d34e04c6426439066619f412dad16db0301481fc3ba5c743af817a4946bR93-R94
> 
> Could you please verify [ghrd1.txt](https://github.com/zero88/gh-release-downloader/files/10712564/ghrd1.txt) to see if it works for you? (remove suffix `.txt`)

**Comment by zero88** [comment]
Thank you!!!
I closed this PR because my PR has already included your support.

**Pull request closed without merging**
